name: Package Application with Pyinstaller

on:
  push:
    branches: [ main, dev, rewrite ]
  pull_request:
    branches: [ main, dev, rewrite ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: tinet-bridge-win
        path: src/dist/windows